<?php

/**************************************************************************
 * ObjetsType.php, pokemon Android
 *
 * Copyright 2016
 * Description : 
 * Author(s)   : Harmony
 * Licence     : 
 * Last update : May 27, 2016
 *
 **************************************************************************/

namespace Pokemon\ApiBundle\Form;

use Pokemon\ApiBundle\Form\ObjetsTypeBase;


/**
 * Objets Type
 *
 * This class was generated by the Harmony / Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetsType extends ObjetsTypeBase
{

}
