<?php

/**************************************************************************
 * PositionsType.php, pokemon Android
 *
 * Copyright 2016
 * Description : 
 * Author(s)   : Harmony
 * Licence     : 
 * Last update : May 27, 2016
 *
 **************************************************************************/

namespace Pokemon\ApiBundle\Form;

use Pokemon\ApiBundle\Form\PositionsTypeBase;


/**
 * Positions Type
 *
 * This class was generated by the Harmony / Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionsType extends PositionsTypeBase
{

}
