<?php

/**************************************************************************
 * TypesTypeBase.php, pokemon Android
 *
 * Copyright 2016
 * Description : 
 * Author(s)   : Harmony
 * Licence     : 
 * Last update : May 27, 2016
 *
 **************************************************************************/

namespace Pokemon\ApiBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * Types Type
 *
 * This class was generated by the Harmony / Don't modify this class it will be regenerated by Harmony !
 */
class TypesTypeBase extends AbstractType
{

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('typeDePokemonstypesInternal', 'entity', array(
                'class' => 'PokemonApiBundle:TypeDePokemons',
                'property' => 'id',
                'required' => false))
            ->add('nom')
            ->add('typesfaibleContreInternal', 'entity', array(
                'class' => 'PokemonApiBundle:Types',
                'property' => 'id',
                'required' => false))
            ->add('typesfortContreInternal', 'entity', array(
                'class' => 'PokemonApiBundle:Types',
                'property' => 'id',
                'required' => false))
            
            
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Pokemon\ApiBundle\Entity\Types',
            'csrf_protection' => false
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return '';
    }
}
