<?php

namespace Pokemon\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EntityResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityResourceRepository extends EntityRepository
{
}
