<?php

/**************************************************************************
 * NpcRepository.php, pokemon Android
 *
 * Copyright 2016
 * Description : 
 * Author(s)   : Harmony
 * Licence     : 
 * Last update : May 27, 2016
 *
 **************************************************************************/

namespace Pokemon\ApiBundle\Repository;

use Pokemon\ApiBundle\Repository\NpcRepositoryBase;

/**
 * Npc Repository
 *
 * This class was generated by the Harmony / Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NpcRepository extends NpcRepositoryBase {

}

?>
