<?php

namespace Pokemon\ApiBundle\Controller;

use FOS\RestBundle\Controller\Annotations as Rest;
use FOS\RestBundle\Request\ParamFetcherInterface;

use Nelmio\ApiDocBundle\Annotation\ApiDoc;

use Symfony\Component\HttpFoundation\Request;

use Pokemon\ApiBundle\Form\TypesType;
use Pokemon\ApiBundle\Entity\Types;
use Pokemon\ApiBundle\Controller\RestTypeDePokemonsController;
use Pokemon\ApiBundle\Controller\RestTypesController;
use Pokemon\ApiBundle\Controller\RestSyncController as Controller;

/**
 * Types Repository
 *
 * This class was generated by the Harmony / Doctrine ORM.
 *
 * This class will be regenerated by Harmony. DO NOT MODIFIY THIS CLASS.
 */
class RestTypesControllerBase extends Controller {

    public function getNewEntity() {
        return new Types();
    }

    /**=========================================================================
     * CRUD REST
     *========================================================================*/

    /**
     * GET /{id}
     *
     * @param string typesId
     * @return Response
     * @Rest\Get("/{id}")
     * @ApiDoc(
     *   resource=true,
     *   section="Rest CRUD Types",
     *   description="Show entity"
     * )
     * @return type
     */
    public function getTypesAction($id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $data = $entityManager->getRepository('PokemonApiBundle:Types')->findOneById($id);
        $view = $this->view($data, 200);
        return $this->handleView($view);
    }

    /**
     * POST
     *
     * @Rest\Post("")
     * @ApiDoc(
     *   resource=true,
     *   section="Rest CRUD Types",
     *   description="Create entity",
     *   requirements={
     *      {
     *          "name"="typeDePokemonstypesInternal",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The typeDePokemonstypesInternal types",
     *      },
     *      {
     *          "name"="nom",
     *          "dataType"="string",
     *          "requirement"="",
     *          "description"="The nom types",
     *      },
     *      {
     *          "name"="typesfaibleContreInternal",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The typesfaibleContreInternal types",
     *      },
     *      {
     *          "name"="faibleContre",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The faibleContre types",
     *      },
     *      {
     *          "name"="typesfortContreInternal",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The typesfortContreInternal types",
     *      },
     *      {
     *          "name"="fortContre",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The fortContre types",
     *      },
     *   }
     * )
     * @return type
     */
    public function createTypesAction(Request $request) {
        $entity = new Types();

        $form = $this->createForm(new TypesType(), $entity, array(
            'allow_extra_fields' => true
        ));
        $form->submit($request);

        if ($form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($entity);
            $entityManager->flush();
            $view = $this->view($entity, 200);
        } else {
            $view = $this->view(array("error" => "Parameters entity isn't valid" . $form->getErrors()), 400);
        }

        return $this->handleView($view);
    }

    /**
     * GET
     *
     * @Rest\Get("")
     * @Rest\QueryParam(name="page", nullable=true, requirements="\d+", default="0", description="Number of the page")
     * @Rest\QueryParam(name="quantity", nullable=true, requirements="\d+", default="0", description="Quantity of entities per page")
     * @param ParamFetcher $paramFetcher
     * @ApiDoc(
     *   resource=true,
     *   section="Rest CRUD Types",
     *   description="Show all entities",
     *   requirements={
     *   }
     * )
     * @return type
     */
    public function getAllTypesAction(ParamFetcherInterface $paramFetcher)
    {
        $repository = $this->getDoctrine()->getRepository('PokemonApiBundle:Types');

        $page = $paramFetcher->get('page');
        $quantity = $paramFetcher->get('quantity');

        $data = $repository->getList($page, $quantity);

        if ($data) {
            $view = $this->view(array("Typess" => $data), 200);
        } else {
            $view = $this->view(null, 204);
        }

        return $this->handleView($view);
    }

    /**
     * PUT /{id}
     *
     * @Rest\Put("/{id}")
     * @ApiDoc(
     *   resource=true,
     *   section="Rest CRUD Types",
     *   description="Update entity",
     *   requirements={
     *      {
     *          "name"="typeDePokemonstypesInternal",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The typeDePokemonstypesInternal types",
     *      },
     *      {
     *          "name"="nom",
     *          "dataType"="string",
     *          "requirement"="",
     *          "description"="The nom types",
     *      },
     *      {
     *          "name"="typesfaibleContreInternal",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The typesfaibleContreInternal types",
     *      },
     *      {
     *          "name"="faibleContre",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The faibleContre types",
     *      },
     *      {
     *          "name"="typesfortContreInternal",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The typesfortContreInternal types",
     *      },
     *      {
     *          "name"="fortContre",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The fortContre types",
     *      },
     *   }
     * )
     * @return type
     */
    public function updateTypesAction($id, Request $request)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entity = $entityManager->getRepository('PokemonApiBundle:Types')
            ->findOneById($id);

        $form = $this->createForm(new TypesType(), $entity, array(
            'allow_extra_fields' => true
        ));

        $form->submit($request, false);

        if ($form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($entity);
            $entityManager->flush();
            $view = $this->view($entity, 200);
        } else {
            $view = $this->view(array("error" => "Parameters entity isn't valid"), 400);
        }

        return $this->handleView($view);
    }

    /**
     * DELETE /{id}
     *
     * @Rest\Delete("/{id}")
     * @ApiDoc(
     *   resource=true,
     *   section="Rest CRUD Types",
     *   description="Delete entity",
     * )
     * @return type
     */
    public function deleteTypesAction($id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entity = $entityManager->getRepository('PokemonApiBundle:Types')
            ->find(array("id" => $id));

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Types entity');
        }

        $entityManager->remove($entity);
        $entityManager->flush();

        $view = $this->view($entity, 200);
        return $this->handleView($view);
    }


}

?>