<?php

namespace Pokemon\ApiBundle\Controller;

use FOS\RestBundle\Controller\Annotations as Rest;
use FOS\RestBundle\Request\ParamFetcherInterface;

use Nelmio\ApiDocBundle\Annotation\ApiDoc;

use Symfony\Component\HttpFoundation\Request;

use Pokemon\ApiBundle\Form\PokemonsType;
use Pokemon\ApiBundle\Entity\Pokemons;
use Pokemon\ApiBundle\Controller\RestNpcController;
use Pokemon\ApiBundle\Controller\RestTypeDePokemonsController;
use Pokemon\ApiBundle\Controller\RestAttaquesController;
use Pokemon\ApiBundle\Controller\RestSyncController as Controller;

/**
 * Pokemons Repository
 *
 * This class was generated by the Harmony / Doctrine ORM.
 *
 * This class will be regenerated by Harmony. DO NOT MODIFIY THIS CLASS.
 */
class RestPokemonsControllerBase extends Controller {

    public function getNewEntity() {
        return new Pokemons();
    }

    /**=========================================================================
     * CRUD REST
     *========================================================================*/

    /**
     * GET /{id}
     *
     * @param string pokemonsId
     * @return Response
     * @Rest\Get("/{id}")
     * @ApiDoc(
     *   resource=true,
     *   section="Rest CRUD Pokemons",
     *   description="Show entity"
     * )
     * @return type
     */
    public function getPokemonsAction($id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $data = $entityManager->getRepository('PokemonApiBundle:Pokemons')->findOneById($id);
        $view = $this->view($data, 200);
        return $this->handleView($view);
    }

    /**
     * POST
     *
     * @Rest\Post("")
     * @ApiDoc(
     *   resource=true,
     *   section="Rest CRUD Pokemons",
     *   description="Create entity",
     *   requirements={
     *      {
     *          "name"="npcpokemonsInternal",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The npcpokemonsInternal pokemons",
     *      },
     *      {
     *          "name"="surnom",
     *          "dataType"="string",
     *          "requirement"="",
     *          "description"="The surnom pokemons",
     *      },
     *      {
     *          "name"="niveau",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The niveau pokemons",
     *      },
     *      {
     *          "name"="capture",
     *          "dataType"="datetime",
     *          "requirement"="",
     *          "description"="The capture pokemons",
     *      },
     *      {
     *          "name"="typePokemon",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The typePokemon pokemons",
     *      },
     *      {
     *          "name"="attaque1",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The attaque1 pokemons",
     *      },
     *      {
     *          "name"="attaque2",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The attaque2 pokemons",
     *      },
     *      {
     *          "name"="attaque3",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The attaque3 pokemons",
     *      },
     *      {
     *          "name"="attaque4",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The attaque4 pokemons",
     *      },
     *   }
     * )
     * @return type
     */
    public function createPokemonsAction(Request $request) {
        $entity = new Pokemons();

        $form = $this->createForm(new PokemonsType(), $entity, array(
            'allow_extra_fields' => true
        ));
        $form->submit($request);

        if ($form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($entity);
            $entityManager->flush();
            $view = $this->view($entity, 200);
        } else {
            $view = $this->view(array("error" => "Parameters entity isn't valid" . $form->getErrors()), 400);
        }

        return $this->handleView($view);
    }

    /**
     * GET
     *
     * @Rest\Get("")
     * @Rest\QueryParam(name="page", nullable=true, requirements="\d+", default="0", description="Number of the page")
     * @Rest\QueryParam(name="quantity", nullable=true, requirements="\d+", default="0", description="Quantity of entities per page")
     * @param ParamFetcher $paramFetcher
     * @ApiDoc(
     *   resource=true,
     *   section="Rest CRUD Pokemons",
     *   description="Show all entities",
     *   requirements={
     *   }
     * )
     * @return type
     */
    public function getAllPokemonsAction(ParamFetcherInterface $paramFetcher)
    {
        $repository = $this->getDoctrine()->getRepository('PokemonApiBundle:Pokemons');

        $page = $paramFetcher->get('page');
        $quantity = $paramFetcher->get('quantity');

        $data = $repository->getList($page, $quantity);

        if ($data) {
            $view = $this->view(array("Pokemonss" => $data), 200);
        } else {
            $view = $this->view(null, 204);
        }

        return $this->handleView($view);
    }

    /**
     * PUT /{id}
     *
     * @Rest\Put("/{id}")
     * @ApiDoc(
     *   resource=true,
     *   section="Rest CRUD Pokemons",
     *   description="Update entity",
     *   requirements={
     *      {
     *          "name"="npcpokemonsInternal",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The npcpokemonsInternal pokemons",
     *      },
     *      {
     *          "name"="surnom",
     *          "dataType"="string",
     *          "requirement"="",
     *          "description"="The surnom pokemons",
     *      },
     *      {
     *          "name"="niveau",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The niveau pokemons",
     *      },
     *      {
     *          "name"="capture",
     *          "dataType"="datetime",
     *          "requirement"="",
     *          "description"="The capture pokemons",
     *      },
     *      {
     *          "name"="typePokemon",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The typePokemon pokemons",
     *      },
     *      {
     *          "name"="attaque1",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The attaque1 pokemons",
     *      },
     *      {
     *          "name"="attaque2",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The attaque2 pokemons",
     *      },
     *      {
     *          "name"="attaque3",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The attaque3 pokemons",
     *      },
     *      {
     *          "name"="attaque4",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The attaque4 pokemons",
     *      },
     *   }
     * )
     * @return type
     */
    public function updatePokemonsAction($id, Request $request)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entity = $entityManager->getRepository('PokemonApiBundle:Pokemons')
            ->findOneById($id);

        $form = $this->createForm(new PokemonsType(), $entity, array(
            'allow_extra_fields' => true
        ));

        $form->submit($request, false);

        if ($form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($entity);
            $entityManager->flush();
            $view = $this->view($entity, 200);
        } else {
            $view = $this->view(array("error" => "Parameters entity isn't valid"), 400);
        }

        return $this->handleView($view);
    }

    /**
     * DELETE /{id}
     *
     * @Rest\Delete("/{id}")
     * @ApiDoc(
     *   resource=true,
     *   section="Rest CRUD Pokemons",
     *   description="Delete entity",
     * )
     * @return type
     */
    public function deletePokemonsAction($id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entity = $entityManager->getRepository('PokemonApiBundle:Pokemons')
            ->find(array("id" => $id));

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Pokemons entity');
        }

        $entityManager->remove($entity);
        $entityManager->flush();

        $view = $this->view($entity, 200);
        return $this->handleView($view);
    }


}

?>