<?php

namespace Pokemon\ApiBundle\Controller;

use FOS\RestBundle\Controller\Annotations as Rest;
use FOS\RestBundle\Request\ParamFetcherInterface;

use Nelmio\ApiDocBundle\Annotation\ApiDoc;

use Symfony\Component\HttpFoundation\Request;

use Pokemon\ApiBundle\Form\TypeDePokemonsType;
use Pokemon\ApiBundle\Entity\TypeDePokemons;
use Pokemon\ApiBundle\Controller\RestTypesController;
use Pokemon\ApiBundle\Controller\RestSyncController as Controller;

/**
 * TypeDePokemons Repository
 *
 * This class was generated by the Harmony / Doctrine ORM.
 *
 * This class will be regenerated by Harmony. DO NOT MODIFIY THIS CLASS.
 */
class RestTypeDePokemonsControllerBase extends Controller {

    public function getNewEntity() {
        return new TypeDePokemons();
    }

    /**=========================================================================
     * CRUD REST
     *========================================================================*/

    /**
     * GET /{id}
     *
     * @param string typeDePokemonsId
     * @return Response
     * @Rest\Get("/{id}")
     * @ApiDoc(
     *   resource=true,
     *   section="Rest CRUD TypeDePokemons",
     *   description="Show entity"
     * )
     * @return type
     */
    public function getTypeDePokemonsAction($id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $data = $entityManager->getRepository('PokemonApiBundle:TypeDePokemons')->findOneById($id);
        $view = $this->view($data, 200);
        return $this->handleView($view);
    }

    /**
     * POST
     *
     * @Rest\Post("")
     * @ApiDoc(
     *   resource=true,
     *   section="Rest CRUD TypeDePokemons",
     *   description="Create entity",
     *   requirements={
     *      {
     *          "name"="nom",
     *          "dataType"="string",
     *          "requirement"="",
     *          "description"="The nom typeDePokemons",
     *      },
     *      {
     *          "name"="attaque",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The attaque typeDePokemons",
     *      },
     *      {
     *          "name"="attaque_spe",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The attaque_spe typeDePokemons",
     *      },
     *      {
     *          "name"="defence",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The defence typeDePokemons",
     *      },
     *      {
     *          "name"="defence_spe",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The defence_spe typeDePokemons",
     *      },
     *      {
     *          "name"="vitesse",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The vitesse typeDePokemons",
     *      },
     *      {
     *          "name"="pv",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The pv typeDePokemons",
     *      },
     *      {
     *          "name"="types",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The types typeDePokemons",
     *      },
     *   }
     * )
     * @return type
     */
    public function createTypeDePokemonsAction(Request $request) {
        $entity = new TypeDePokemons();

        $form = $this->createForm(new TypeDePokemonsType(), $entity, array(
            'allow_extra_fields' => true
        ));
        $form->submit($request);

        if ($form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($entity);
            $entityManager->flush();
            $view = $this->view($entity, 200);
        } else {
            $view = $this->view(array("error" => "Parameters entity isn't valid" . $form->getErrors()), 400);
        }

        return $this->handleView($view);
    }

    /**
     * GET
     *
     * @Rest\Get("")
     * @Rest\QueryParam(name="page", nullable=true, requirements="\d+", default="0", description="Number of the page")
     * @Rest\QueryParam(name="quantity", nullable=true, requirements="\d+", default="0", description="Quantity of entities per page")
     * @param ParamFetcher $paramFetcher
     * @ApiDoc(
     *   resource=true,
     *   section="Rest CRUD TypeDePokemons",
     *   description="Show all entities",
     *   requirements={
     *   }
     * )
     * @return type
     */
    public function getAllTypeDePokemonsAction(ParamFetcherInterface $paramFetcher)
    {
        $repository = $this->getDoctrine()->getRepository('PokemonApiBundle:TypeDePokemons');

        $page = $paramFetcher->get('page');
        $quantity = $paramFetcher->get('quantity');

        $data = $repository->getList($page, $quantity);

        if ($data) {
            $view = $this->view(array("TypeDePokemonss" => $data), 200);
        } else {
            $view = $this->view(null, 204);
        }

        return $this->handleView($view);
    }

    /**
     * PUT /{id}
     *
     * @Rest\Put("/{id}")
     * @ApiDoc(
     *   resource=true,
     *   section="Rest CRUD TypeDePokemons",
     *   description="Update entity",
     *   requirements={
     *      {
     *          "name"="nom",
     *          "dataType"="string",
     *          "requirement"="",
     *          "description"="The nom typeDePokemons",
     *      },
     *      {
     *          "name"="attaque",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The attaque typeDePokemons",
     *      },
     *      {
     *          "name"="attaque_spe",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The attaque_spe typeDePokemons",
     *      },
     *      {
     *          "name"="defence",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The defence typeDePokemons",
     *      },
     *      {
     *          "name"="defence_spe",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The defence_spe typeDePokemons",
     *      },
     *      {
     *          "name"="vitesse",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The vitesse typeDePokemons",
     *      },
     *      {
     *          "name"="pv",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The pv typeDePokemons",
     *      },
     *      {
     *          "name"="types",
     *          "dataType"="integer",
     *          "requirement"="",
     *          "description"="The types typeDePokemons",
     *      },
     *   }
     * )
     * @return type
     */
    public function updateTypeDePokemonsAction($id, Request $request)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entity = $entityManager->getRepository('PokemonApiBundle:TypeDePokemons')
            ->findOneById($id);

        $form = $this->createForm(new TypeDePokemonsType(), $entity, array(
            'allow_extra_fields' => true
        ));

        $form->submit($request, false);

        if ($form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($entity);
            $entityManager->flush();
            $view = $this->view($entity, 200);
        } else {
            $view = $this->view(array("error" => "Parameters entity isn't valid"), 400);
        }

        return $this->handleView($view);
    }

    /**
     * DELETE /{id}
     *
     * @Rest\Delete("/{id}")
     * @ApiDoc(
     *   resource=true,
     *   section="Rest CRUD TypeDePokemons",
     *   description="Delete entity",
     * )
     * @return type
     */
    public function deleteTypeDePokemonsAction($id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entity = $entityManager->getRepository('PokemonApiBundle:TypeDePokemons')
            ->find(array("id" => $id));

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find TypeDePokemons entity');
        }

        $entityManager->remove($entity);
        $entityManager->flush();

        $view = $this->view($entity, 200);
        return $this->handleView($view);
    }


}

?>