<?php

/**************************************************************************
 * SyncController.php, pokemon Android
 *
 * Copyright 2016
 * Description : 
 * Author(s)   : Harmony
 * Licence     : 
 * Last update : Jun 22, 2016
 *
 **************************************************************************/

namespace Pokemon\ApiBundle\Controller;


/**
 * Sync Controller
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * controller methods below.
 */
class SyncController extends SyncControllerBase {

}

?>
